# Generated by Django 4.2.6 on 2023-11-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperiod',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalperiod',
            name='end_year',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalperiod',
            name='start_year',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
