# Generated by Django 4.2.6 on 2023-11-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_historicalperiod_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperiod',
            name='end_year',
            field=models.SmallIntegerField(null=True),
        ),
    ]
