# Generated by Django 4.2.6 on 2023-12-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_alter_historicalperiod_end_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='historical_area',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalperiod',
            name='end_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
