# Generated by Django 4.2.6 on 2023-12-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_remove_location_historical_area_event_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalarea',
            name='actual_name',
        ),
        migrations.AddField(
            model_name='event',
            name='historical_area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='explore.historicalarea'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
