# Generated by Django 4.2.6 on 2023-12-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_category_remove_event_category_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(choices=[('War', 'War'), ('Battle', 'Battle'), ('Invasion', 'Invasion'), ('Uprising', 'Uprising'), ('Revolution', 'Revolution'), ('Human disaster', 'Human_disaster'), ('Natural disaster', 'Natural_disaster'), ('Treaty', 'Treaty'), ('Truce', 'Truce'), ('Discovery', 'Discovery'), ('Epidemic', 'Epidemic'), ('Succession', 'Succession'), ('Social', 'Social'), ('Religious', 'Religious'), ('Cultural', 'Cultural')], max_length=30),
        ),
    ]
