# Generated by Django 4.2.6 on 2023-12-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_alter_eventtype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='event_date',
        ),
    ]
