# Generated by Django 4.2.6 on 2023-12-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0008_rename_date_event_event_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='explore_event',
        ),
    ]
