# Generated by Django 4.2.6 on 2023-12-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0009_alter_event_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
    ]
