# Generated by Django 4.2.6 on 2023-12-26 09:46
import urllib

from django.db import migrations
from explore.models import MapLocation, Event
import requests
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0011_maplocation'),
    ]

    operations = [
    ]
