# Generated by Django 4.2.6 on 2023-12-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0012_populate_map_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11),
        ),
    ]
