# Generated by Django 4.2.6 on 2024-01-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0016_user_createddate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
