# Generated by Django 4.2.6 on 2024-02-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0018_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz_id',
            field=models.SmallIntegerField(),
        ),
    ]
