# Generated by Django 4.2.6 on 2024-02-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0020_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.quiz'),
        ),
    ]
