# Generated by Django 4.2.6 on 2024-02-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0021_alter_question_quiz_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
