# Generated by Django 4.2.6 on 2024-03-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0022_rename_quiz_id_question_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='historical_area',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
