# Generated by Django 4.2.6 on 2024-03-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0023_remove_event_historical_area_remove_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tag',
        ),
    ]
