# Generated by Django 4.2.6 on 2024-04-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0026_alter_eventtype_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalArea',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
