# Generated by Django 4.2.6 on 2024-04-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0027_delete_historicalarea_delete_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
